import { NgxUiLoaderConfig } from "ngx-ui-loader";

export const ngxUiLoaderConfig: NgxUiLoaderConfig = {
  bgsColor: "#b9b9b9",
  bgsOpacity: 1,
  bgsPosition: "center-center",
  bgsSize: 100,
  bgsType: "square-jelly-box",
  blur: 15,
  delay: 0,
  fastFadeOut: true,
  fgsColor: "#34b5b8",
  fgsPosition: "center-center",
  fgsSize: 100,
  fgsType: "square-jelly-box",
  gap: 150,
  logoPosition: "center-center",
  logoSize: 120,
  logoUrl: "",
  masterLoaderId: "master",
  overlayBorderRadius: "0",
  overlayColor: "rgba(255,255,255,0.51)",
  pbColor: "#34b5b8",
  pbDirection: "ltr",
  pbThickness: 4,
  hasProgressBar: true,
  text: "",
  textColor: "#FFFFFF",
  textPosition: "center-center",
  maxTime: -1,
  minTime: 300,
};
